### ISSUE TITLE
epel repository enabled when course is set to offline

### ISSUE THREAD

**Issue by choonming** [puppetlabs/pltraining-classroom#15]
In the repositories.pp:

  if $manageyum and $::osfamily == 'RedHat' {
    yumrepo { $repositories:
      enabled => $offline ? {
        true  => '0',
        false => '1',
      },
    }
    # Don't choke if another module has "include epel"
    if ! defined(Class['epel']) {
      class { 'epel':
        epel_enabled => $offline,
      }
    }

When a user sets $offline = true, the epel_enabled's value will become true as well. Shouldn't there be a selector state similar tot he yumrepo resource above it?

**Comment by binford2k** [comment]
https://tickets.puppetlabs.com/browse/TRAINTECH-106
